web_dictionary = {
	'web amazon':'https://www.amazon.com',
	'web canon':'https://www.usa.canon.com/internet/portal/us/home/support/product-finder/support-printers',
	'web cisco':'https://www.cisco.com/c/en/us/support/all-products.html',
	'web dell':'https://www.dell.com/support/home/us/en/04/Products/?app=warranty',
	'web git':'https://github.com/',
	'web gns3':'https://www.gns3.com',
	'web google':'https://www.google.com',
	'web hp':'https://support.hp.com/us-en',
	'web igloo':'https://easyigloo.org',
	'web ms':'https://support.microsoft.com/en-us',
	'web netmiko':'https://pynet.twb-tech.com/blog/automation/netmiko.html',
	'web newegg':'https://www.newegg.com/',
	'web python':'https://www.python.org/',
	'web reddit':'https://www.reddit.com',
	'web rfc':'https://www.rfc-editor.org/rfc-index.html',
	'web ruby':'https://www.ruby-lang.org/en/',
	'web stackoverflow':'https://stackoverflow.com',
	'web superuser':'https://superuser.com/',
	'web technet':'https://technet.microsoft.com/library/',
	'web wiki':'https://www.wikipedia.org/',
}