# Dictionary that matches incomplete user input with associated help files
help_dictionary = {

    '?':'.\\help-files\\helpShort.txt',
    '???':'.\\help-files\\helpLong.txt',
    'about':'.\\help-files\\helpAbout.txt',
    'crypto ?':'.\\help-files\\helpCrypto.txt',
    'crypto connect':'.\\help-files\\helpCryptoConnect.txt',
    'crypto del':'.\\help-files\\helpCryptoDel.txt',
    'crypto generate':'.\\help-files\\helpCryptoGenerate.txt',
    'crypto ipsec 3des ?':'.\\help-files\\helpCryptoIpsecAuth.txt',
    'crypto ipsec 3des md5 ?':'.\\help-files\\helpCryptoIpsecGroups.txt',
    'crypto ipsec 3des md5':'.\\help-files\\helpCryptoIpsecGroups.txt',
    'crypto ipsec 3des sha256 ?':'.\\help-files\\helpCryptoIpsecGroups.txt',
    'crypto ipsec 3des sha256':'.\\help-files\\helpCryptoIpsecGroups.txt',
    'crypto ipsec 3des':'.\\help-files\\helpCryptoIpsecAuth.txt',
    'crypto ipsec ?':'.\\help-files\\helpCryptoIpsecEncrypt.txt',
    'crypto ipsec aes128 ?':'.\\help-files\\helpCryptoIpsecAuth.txt',
    'crypto ipsec aes128 md5 ?':'.\\help-files\\helpCryptoIpsecGroups.txt',
    'crypto ipsec aes128 md5':'.\\help-files\\helpCryptoIpsecGroups.txt',
    'crypto ipsec aes128 sha256 ?':'.\\help-files\\helpCryptoIpsecGroups.txt',
    'crypto ipsec aes128 sha256':'.\\help-files\\helpCryptoIpsecGroups.txt',
    'crypto ipsec aes128':'.\\help-files\\helpCryptoIpsecAuth.txt',
    'crypto ipsec aes256 ?':'.\\help-files\\helpCryptoIpsecAuth.txt',
    'crypto ipsec aes256 md5 ?':'.\\help-files\\helpCryptoIpsecGroups.txt',
    'crypto ipsec aes256 md5':'.\\help-files\\helpCryptoIpsecGroups.txt',
    'crypto ipsec aes256 sha256 ?':'.\\help-files\\helpCryptoIpsecGroups.txt',
    'crypto ipsec aes256 sha256':'.\\help-files\\helpCryptoIpsecGroups.txt',
    'crypto ipsec aes256':'.\\help-files\\helpCryptoIpsecAuth.txt',
    'crypto ipsec des ?':'.\\help-files\\helpCryptoIpsecAuth.txt',
    'crypto ipsec des md5 ?':'.\\help-files\\helpCryptoIpsecGroups.txt',
    'crypto ipsec des md5':'.\\help-files\\helpCryptoIpsecGroups.txt',
    'crypto ipsec des sha256 ?':'.\\help-files\\helpCryptoIpsecGroups.txt',
    'crypto ipsec des sha256':'.\\help-files\\helpCryptoIpsecGroups.txt',
    'crypto ipsec des':'.\\help-files\\helpCryptoIpsecAuth.txt',
    'crypto ipsec':'.\\help-files\\helpCryptoIpsecEncrypt.txt',
    'crypto pptp ?':'.\\help-files\\helpCryptoPptpAuth.txt',
    'crypto pptp':'.\\help-files\\helpCryptoPptpAuth.txt',
    'crypto':'.\\help-files\\helpCrypto.txt',
    'crypto':'.\\help-files\\helpCrypto.txt',
    'deploy':'.\\help-files\\helpDeploy.txt',
    'deploy ?':'.\\help-files\\helpDeploy.txt',
    'fwall ?':'.\\help-files\\helpFwall.txt',
    'fwall':'.\\help-files\\helpFwall.txt',
    'get ?':'.\\help-files\\helpGetCmds.txt',
    'get linux ?':'.\\help-files\\helpGetLinux.txt',
    'get linux':'.\\help-files\\helpGetLinux.txt',
    'get python ?':'.\\help-files\\helpGetPython.txt',
    'get python':'.\\help-files\\helpGetPython.txt',
    'get ruby ?':'.\\help-files\\helpGetRuby.txt',
    'get ruby':'.\\help-files\\helpGetRuby.txt',
    'get':'.\\help-files\\helpGetCmds.txt',
    'install ?':'.\\help-files\\helpInstall.txt',
    'install ad-cs ?':'.\\help-files\\helpInstallAdcs.txt',
    'install ad-cs enrollment ?':'.\\help-files\\helpInstallAdcsEnrollment.txt',
    'install ad-cs enrollment':'.\\help-files\\helpInstallAdcsEnrollment.txt',
    'install ad-cs':'.\\help-files\\helpInstallAdcs.txt',
    'install ad-rights ?':'.\\help-files\\helpInstallAdRights.txt',
    'install ad-rights':'.\\help-files\\helpInstallAdRights.txt',
    'install app-server ?':'.\\help-files\\helpInstallAppServer.txt',
    'install app-server transaction ?':'.\\help-files\\helpInstallAppServerTransaction.txt',
    'install app-server transaction':'.\\help-files\\helpInstallAppServerTransaction.txt',
    'install app-server':'.\\help-files\\helpInstallAppServer.txt',
    'install bitlocker ?':'.\\help-files\\helpInstallBitlocker.txt',
    'install bitlocker':'.\\help-files\\helpInstallBitlocker.txt',
    'install bits ?':'.\\help-files\\helpInstallBits.txt',
    'install bits ?':'.\\help-files\\helpInstallBits.txt',
    'install bits':'.\\help-files\\helpInstallBits.txt',
    'install bits':'.\\help-files\\helpInstallBits.txt',
    'install dotnet ?':'.\\help-files\\helpInstallDotnet.txt',
    'install dotnet':'.\\help-files\\helpInstallDotnet.txt',
    'install dotnet45 ?':'.\\help-files\\helpInstallDotnet45.txt',
    'install dotnet45':'.\\help-files\\helpInstallDotnet45.txt',
    'install feature ?':'.\\help-files\\helpInstallFeature.txt',
    'install feature':'.\\help-files\\helpInstallFeature.txt',
    'install hyperv ?':'.\\help-files\\helpInstallHyperv.txt',
    'install hyperv':'.\\help-files\\helpInstallHyperv.txt',
    'install iis ?':'.\\help-files\\helpInstallIis.txt',
    'install iis':'.\\help-files\\helpInstallIis.txt',
    'install iscsi ?':'.\\help-files\\helpInstallIscsi.txt',
    'install iscsi':'.\\help-files\\helpInstallIscsi.txt',
    'install msmq ?':'.\\help-files\\helpInstallMsmq.txt',
    'install msmq':'.\\help-files\\helpInstallMsmq.txt',
    'install npas ?':'.\\help-files\\helpInstallNpas.txt',
    'install npas':'.\\help-files\\helpInstallNpas.txt',
    'install rdp ?':'.\\help-files\\helpInstallRdp.txt',
    'install rdp':'.\\help-files\\helpInstallRdp.txt',
    'install rsat ?':'.\\help-files\\helpInstallRsat.txt',
    'install rsat':'.\\help-files\\helpInstallRsat.txt',
    'install update-service ?':'.\\help-files\\helpInstallUpdateService.txt',
    'install update-service':'.\\help-files\\helpInstallUpdateService.txt',
    'install wds ?':'.\\help-files\\helpInstallWds.txt',
    'install wds':'.\\help-files\\helpInstallWds.txt',
    'install':'.\\help-files\\helpInstall.txt',
    'int ?':'.\\help-files\\helpInt.txt',
    'int disable ?':'.\\help-files\\helpInt.txt',
    'int enable ?':'.\\help-files\\helpInt.txt',
    'int disable':'.\\help-files\\helpInt.txt',
    'int enable':'.\\help-files\\helpInt.txt',
    'int reset ?':'.\\help-files\\helpInt.txt',
    'int reset':'.\\help-files\\helpInt.txt',
    'int':'.\\help-files\\helpInt.txt',
    'int':'.\\help-files\\helpInt.txt',
    'ip ?':'.\\help-files\\helpIp.txt',
    'ip address ?':'.\\help-files\\helpIpAddress.txt',
    'ip address':'.\\help-files\\helpIpAddress.txt',
    'ip icmp ?':'.\\help-files\\helpIcmp.txt',
    'ip icmp redirect ?':'.\\help-files\\helpIpIcmpRedirect.txt',
    'ip icmp redirect':'.\\help-files\\helpIpIcmpRedirect.txt',
    'ip icmp':'.\\help-files\\helpIcmp.txt',
    'ip igmp ?':'.\\help-files\\helpIgmp.txt',
    'ip igmp':'.\\help-files\\helpIgmp.txt',
    'ip multicast ?':'.\\help-files\\helpIpMulticast.txt',
    'ip multicast':'.\\help-files\\helpIpMulticast.txt',
    'ip route ?':'.\\help-files\\helpIpRouteLong.txt',
    'ip route':'.\\help-files\\helpIpRouteLong.txt',
    'ip route-cache ?':'.\\help-files\\helpIpRouteCache.txt',
    'ip route-cache':'.\\help-files\\helpIpRouteCache.txt',
    'ip source-route ?':'.\\help-files\\helpIpSourceRoute.txt',
    'ip source-route':'.\\help-files\\helpIpSourceRoute.txt',
    'ip tcp ?':'.\\help-files\\helpIpTcp.txt',
    'ip tcp auto-tune ?':'.\\help-files\\helpIpTcpAutotune.txt',
    'ip tcp auto-tune':'.\\help-files\\helpIpTcpAutotune.txt',
    'ip tcp ecn ?':'.\\help-files\\helpIpTcpEcn.txt',
    'ip tcp ecn':'.\\help-files\\helpIpTcpEcn.txt',
    'ip tcp mpp ?':'.\\help-files\\helpIpTcpMpp.txt',
    'ip tcp mpp':'.\\help-files\\helpIpTcpMpp.txt',
    'ip tcp port-range ?':'.\\help-files\\helpIpTcpPortRange.txt',
    'ip tcp port-range':'.\\help-files\\helpIpTcpPortRange.txt',
    'ip tcp provider ?':'.\\help-files\\helpIpTcpProvider.txt',
    'ip tcp provider':'.\\help-files\\helpIpTcpProvider.txt',
    'ip tcp timestamp ?':'.\\help-files\\helpIpTcpTimestamp.txt',
    'ip tcp timestamp':'.\\help-files\\helpIpTcpTimestamp.txt',
    'ip tcp window-restart ?':'.\\help-files\\helpIpTcpWindowRestart.txt',
    'ip tcp window-restart':'.\\help-files\\helpIpTcpWindowRestart.txt',
    'ip tcp':'.\\help-files\\helpIpTcp.txt',
    'ip ttl ?':'.\\help-files\\helpIpTtl.txt',
    'ip ttl':'.\\help-files\\helpIpTtl.txt',
    'ip':'.\\help-files\\helpIp.txt',
    'man ?':'.\\help-files\\man.txt',
    'man':'.\\help-files\\man.txt',
    'net ?':'.\\help-files\\helpNet.txt',
    'net':'.\\help-files\\helpNet.txt',
    'no ip route':'.\\help-files\\helpIpRouteRemove.txt',
    'no bgp ?':'.\\help-files\\helpNoBgp.txt',
    'no bgp aggregate ?':'.\\help-files\\helpBgpAdvert.txt',
    'no bgp aggregate':'.\\help-files\\helpBgpAdvert.txt',
    'no bgp peer ?':'.\\help-files\\helpBgpPeer.txt',
    'no bgp peer':'.\\help-files\\helpBgpPeer.txt',
    'no bgp':'.\\help-files\\helpNoBgp.txt',
    'powershell ?':'.\\help-files\\helpPowershell.txt',
    'powershell policy ?':'.\\help-files\\helpPowershellPolicy.txt',
    'powershell policy':'.\\help-files\\helpPowershellPolicy.txt',
    'powershell':'.\\help-files\\helpPowershell.txt',
    'bgp ?':'.\\help-files\\helpBgp.txt',
    'bgp aggregate ?':'.\\help-files\\helpBgpAdvert.txt',
    'bgp aggregate':'.\\help-files\\helpBgpAggregate.txt',
    'bgp advertise':'.\\help-files\\helpBgpAdvertise.txt',
    'bgp advertise ?':'.\\help-files\\helpBgpAdvertise.txt',
    'bgp hold-time ?':'.\\help-files\\helpBgpHold.txt',
    'bgp hold-time':'.\\help-files\\helpBgpHold.txt',
    'bgp id ?':'.\\help-files\\helpBgpId.txt',
    'bgp id':'.\\help-files\\helpBgpId.txt',
    'bgp peer ?':'.\\help-files\\helpBgpPeer.txt',
    'bgp peer':'.\\help-files\\helpBgpPeer.txt',
    'bgp weight ?':'.\\help-files\\helpBgpWeight.txt',
    'bgp weight':'.\\help-files\\helpBgpWeight.txt',
    'bgp':'.\\help-files\\helpBgp.txt',
    'show ?':'.\\help-files\\helpShowCmds.txt',
    'show bgp ?':'.\\help-files\\helpShowBgp.txt',
    'show bgp':'.\\help-files\\helpShowBgp.txt',
    'show dns ?':'.\\help-files\\helpShowDns.txt',
    'show dns':'.\\help-files\\helpShowDns.txt',
    'show fwall ?':'.\\help-files\\helpFwallRule.txt',
    'show fwall':'.\\help-files\\helpFwallRule.txt',
    'show ip ?':'.\\help-files\\helpShowIp.txt',
    'show ip':'.\\help-files\\helpShowIp.txt',
    'show ipv6 ?':'.\\help-files\\helpShowIpv6.txt',
    'show ipv6':'.\\help-files\\helpShowIpv6.txt',
    'show log ?':'.\\help-files\\helpShowLog.txt',
    'show log':'.\\help-files\\helpShowLog.txt',
    'show':'.\\help-files\\helpShowCmds.txt',
    'ssh ?':'.\\help-files\\helpSsh.txt',
    'ssh show ?':'.\\help-files\\helpSshShowWrite.txt',
    'ssh show':'.\\help-files\\helpSshShowWrite.txt',
    'ssh write ?':'.\\help-files\\helpSshShowWrite.txt',
    'ssh write':'.\\help-files\\helpSshShowWrite.txt',
    'ssh':'.\\help-files\\helpSsh.txt',
    'tcp ?':'.\\help-files\\helpTcp.txt',
    'tcp ping ?':'.\\help-files\\helpTcpPing.txt',
    'tcp ping':'.\\help-files\\helpTcpPing.txt',
    'tcp scan ?':'.\\help-files\\helpTcpScan.txt',
    'tcp scan':'.\\help-files\\helpTcpScan.txt',
    'tcp':'.\\help-files\\helpTcp.txt',
    'uninstall ?':'.\\help-files\\helpInstall.txt',
    'uninstall ad-cs ?':'.\\help-files\\helpInstallAdcs.txt',
    'uninstall ad-cs enrollment ?':'.\\help-files\\helpInstallAdcsEnrollment.txt',
    'uninstall ad-cs enrollment':'.\\help-files\\helpInstallAdcsEnrollment.txt',
    'uninstall ad-cs':'.\\help-files\\helpInstallAdcs.txt',
    'uninstall ad-rights ?':'.\\help-files\\helpInstallAdRights.txt',
    'uninstall ad-rights':'.\\help-files\\helpInstallAdRights.txt',
    'uninstall app-server ?':'.\\help-files\\helpInstallAppServer.txt',
    'uninstall app-server transaction ?':'.\\help-files\\helpInstallAppServerTransaction.txt',
    'uninstall app-server transaction':'.\\help-files\\helpInstallAppServerTransaction.txt',
    'uninstall app-server':'.\\help-files\\helpInstallAppServer.txt',
    'uninstall bitlocker ?':'.\\help-files\\helpInstallBitlocker.txt',
    'uninstall bitlocker':'.\\help-files\\helpInstallBitlocker.txt',
    'uninstall bits ?':'.\\help-files\\helpInstallBits.txt',
    'uninstall bits ?':'.\\help-files\\helpInstallBits.txt',
    'uninstall bits':'.\\help-files\\helpInstallBits.txt',
    'uninstall bits':'.\\help-files\\helpInstallBits.txt',
    'uninstall dotnet ?':'.\\help-files\\helpInstallDotnet.txt',
    'uninstall dotnet':'.\\help-files\\helpInstallDotnet.txt',
    'uninstall dotnet45 ?':'.\\help-files\\helpInstallDotnet45.txt',
    'uninstall dotnet45':'.\\help-files\\helpInstallDotnet45.txt',
    'uninstall feature ?':'.\\help-files\\helpInstallFeature.txt',
    'uninstall feature':'.\\help-files\\helpInstallFeature.txt',
    'uninstall hyperv ?':'.\\help-files\\helpInstallHyperv.txt',
    'uninstall hyperv':'.\\help-files\\helpInstallHyperv.txt',
    'uninstall iis ?':'.\\help-files\\helpInstallIis.txt',
    'uninstall iis':'.\\help-files\\helpInstallIis.txt',
    'uninstall iscsi ?':'.\\help-files\\helpInstallIscsi.txt',
    'uninstall iscsi':'.\\help-files\\helpInstallIscsi.txt',
    'uninstall msmq ?':'.\\help-files\\helpInstallMsmq.txt',
    'uninstall msmq':'.\\help-files\\helpInstallMsmq.txt',
    'uninstall npas ?':'.\\help-files\\helpInstallNpas.txt',
    'uninstall npas':'.\\help-files\\helpInstallNpas.txt',
    'uninstall rdp ?':'.\\help-files\\helpInstallRdp.txt',
    'uninstall rdp':'.\\help-files\\helpInstallRdp.txt',
    'uninstall rsat ?':'.\\help-files\\helpInstallRsat.txt',
    'uninstall rsat':'.\\help-files\\helpInstallRsat.txt',
    'uninstall update-service ?':'.\\help-files\\helpInstallUpdateService.txt',
    'uninstall update-service':'.\\help-files\\helpInstallUpdateService.txt',
    'uninstall wds ?':'.\\help-files\\helpInstallWds.txt',
    'uninstall wds':'.\\help-files\\helpInstallWds.txt',
    'uninstall':'.\\help-files\\helpInstall.txt',
    'web ?':'.\\help-files\\helpWeb.txt',
    'web':'.\\help-files\\helpWeb.txt',
    'win ?':'.\\help-files\\helpWin.txt',
    'win':'.\\help-files\\helpWin.txt',

}
