manual_dictionary = {
    'man crypto':'https://easyigloo.org/crypto',
    'man fping':'https://easyigloo.org/fping',
    'man fwall':'https://easyigloo.org/fwall',
    'man install':'https://easyigloo.org/install',
    'man int':'https://easyigloo.org/int',
    'man ip':'https://easyigloo.org/pageip',
    'man pshell':'https://easyigloo.org/powershell',
    'man bgp':'https://easyigloo.org/bgp',
    'man show':'https://easyigloo.org/show',
    'man ssh':'https://easyigloo.org/ssh',
    'man tcp':'https://easyigloo.org/tcp',
    'man update':'https://easyigloo.org/update',
    'man web':'https://easyigloo.org/web',
    'man win':'https://easyigloo.org/win',
}
