 # Command dictionary for the server uninstall command set
uninstall_dictionary = {
'uninstall feature ad-cs':'Uninstall-WindowsFeature -Name AD-Certificate',
	'uninstall feature ad-ds':'Uninstall-WindowsFeature -Name AD-Domain-Services',
	'uninstall feature ad-fs':'Uninstall-WindowsFeature -Name ADFS-Federation',
	'uninstall feature ad-rights':'Uninstall-WindowsFeature -Name ADRMS',
	'uninstall feature adlds':'Uninstall-WindowsFeature -Name ADLDS',
	'uninstall feature app-server':'Uninstall-WindowsFeature -Name Application-Server ',
	'uninstall feature biometrics':'Uninstall-WindowsFeature -Name Biometric-Framework ',
	'uninstall feature bitlocker':'Uninstall-WindowsFeature -Name BitLocker ',
	'uninstall feature bits':'Uninstall-WindowsFeature -Name BITS ',
	'uninstall feature branch-cache':'Uninstall-WindowsFeature -Name BranchCache ',
	'uninstall feature cmak':'Uninstall-WindowsFeature -Name CMAK ',
	'uninstall feature dc-bridge':'Uninstall-WindowsFeature -Name Data-Center-Bridging ',
	'uninstall feature desktop-experience':'Uninstall-WindowsFeature -Name Desktop-Experience ',
	'uninstall feature dhcp-server':'Uninstall-WindowsFeature -Name DHCP',
	'uninstall feature direct-access':'Uninstall-WindowsFeature -Name DirectAccess-VPN',
	'uninstall feature direct-play':'Uninstall-WindowsFeature -Name Direct-Play ',
	'uninstall feature dns-server':'Uninstall-WindowsFeature -Name DNS',
	'uninstall feature dotnet':'Uninstall-WindowsFeature -Name NET-Framework-Features',
	'uninstall feature dotnet-core':'Uninstall-WindowsFeature -Name NET-Framework-Core ',
	'uninstall feature dotnet45':'Uninstall-WindowsFeature -Name NET-Framework-45-Features',
	'uninstall feature dotnet45-core':'Uninstall-WindowsFeature -Name NET-Framework-45-Core ',
	'uninstall feature dsc-service':'Uninstall-WindowsFeature -Name DSC-Service ',
	'uninstall feature enhanced-storage':'Uninstall-WindowsFeature -Name EnhancedStorage ',
	'uninstall feature failover-clustering':'Uninstall-WindowsFeature -Name Failover-Clustering ',
	'uninstall feature fax':'Uninstall-WindowsFeature -Name Fax',
	'uninstall feature gpmc':'Uninstall-WindowsFeature -Name GPMC ',
	'uninstall feature handwriting-services':'Uninstall-WindowsFeature -Name InkAndHandwritingServices ',
	'uninstall feature hyperv':'Uninstall-WindowsFeature -Name Hyper-V',
	'uninstall feature iis':'Uninstall-WindowsFeature -Name Web-Server',
	'uninstall feature internet-print-client':'Uninstall-WindowsFeature -Name Internet-Print-Client ',
	'uninstall feature ipam':'Uninstall-WindowsFeature -Name IPAM ',
	'uninstall feature ipam-client':'Uninstall-WindowsFeature -Name IPAM-Client-Feature ',
	'uninstall feature iscsi':'Uninstall-WindowsFeature -Name File-Services',
	'uninstall feature isns':'Uninstall-WindowsFeature -Name ISNS ',
	'uninstall feature lpr-port-monitor':'Uninstall-WindowsFeature -Name LPR-Port-Monitor ',
	'uninstall feature msmq':'Uninstall-WindowsFeature -Name MSMQ ',
	'uninstall feature multipath-io':'Uninstall-WindowsFeature -Name Multipath-IO ',
	'uninstall feature nfs-client':'Uninstall-WindowsFeature -Name NFS-Client ',
	'uninstall feature nlb':'Uninstall-WindowsFeature -Name NLB ',
	'uninstall feature npas':'Uninstall-WindowsFeature -Name NPAS',
	'uninstall feature pnrp':'Uninstall-WindowsFeature -Name PNRP ',
	'uninstall feature print-internet':'Uninstall-WindowsFeature -Name Print-Internet',
	'uninstall feature print-lpd':'Uninstall-WindowsFeature -Name Print-LPD-Service',
	'uninstall feature print-services':'Uninstall-WindowsFeature -Name Print-Services',
	'uninstall feature pshell':'Uninstall-WindowsFeature -Name PowerShell ',
	'uninstall feature pshell-ise':'Uninstall-WindowsFeature -Name PowerShell-ISE ',
	'uninstall feature pshell-root':'Uninstall-WindowsFeature -Name PowerShellRoot ',
	'uninstall feature pshell-v2':'Uninstall-WindowsFeature -Name PowerShell-V2 ',
	'uninstall feature pshell-web-access':'Uninstall-WindowsFeature -Name WindowsPowerShellWebAccess ',
	'uninstall feature qwave':'Uninstall-WindowsFeature -Name qWave ',
	'uninstall feature rdc':'Uninstall-WindowsFeature -Name RDC ',
	'uninstall feature rdp-server':'Uninstall-WindowsFeature -Name Remote-Desktop-Services',
	'uninstall feature remote-access':'Uninstall-WindowsFeature -Name RemoteAccess',
	'uninstall feature remote-assist':'Uninstall-WindowsFeature -Name Remote-Assistance ',
	'uninstall feature routing':'Uninstall-WindowsFeature -Name DirectAccess-VPN',
	'uninstall feature routing':'Uninstall-WindowsFeature -Name Routing',
	'uninstall feature rpc-over-http-proxy':'Uninstall-WindowsFeature -Name RPC-over-HTTP-Proxy',
	'uninstall feature rsat':'Uninstall-WindowsFeature -Name RSAT ',
	'uninstall feature scan-server':'Uninstall-WindowsFeature -Name Print-Scan-Server',
	'uninstall feature search-service':'Uninstall-WindowsFeature -Name Search-Service ',
	'uninstall feature server-backup':'Uninstall-WindowsFeature -Name Windows-Server-Backup ',
	'uninstall feature server-essentials':'Uninstall-WindowsFeature -Name ServerEssentialsRole ',
	'uninstall feature server-gui-mgmt':'Uninstall-WindowsFeature -Name Server-Gui-Mgmt-Infra',
	'uninstall feature server-gui-shell':'Uninstall-WindowsFeature -Name Server-Gui-Shell ',
	'uninstall feature server-media-foundation':'Uninstall-WindowsFeature -Name Server-Media-Foundation ',
	'uninstall feature server-migration':'Uninstall-WindowsFeature -Name Migration ',
	'uninstall feature simple-tcpip':'Uninstall-WindowsFeature -Name Simple-TCPIP ',
	'uninstall feature smb-1':'Uninstall-WindowsFeature -Name FS-SMB1 ',
	'uninstall feature smb-bandwidth-limit':'Uninstall-WindowsFeature -Name FS-SMBBW ',
	'uninstall feature smtp-server':'Uninstall-WindowsFeature -Name SMTP-Server ',
	'uninstall feature smtp-services':'Uninstall-WindowsFeature -Name SNMP-Service ',
	'uninstall feature snmp-wmi-provider':'Uninstall-WindowsFeature -Name SNMP-WMI-Provider ',
	'uninstall feature storage':'Uninstall-WindowsFeature -Name FileAndStorage-Services',
	'uninstall feature telnet-client':'Uninstall-WindowsFeature -Name Telnet-Client ',
	'uninstall feature telnet-server':'Uninstall-WindowsFeature -Name Telnet-Server ',
	'uninstall feature tftp':'Uninstall-WindowsFeature -Name TFTP-Client ',
	'uninstall feature update-services':'Uninstall-WindowsFeature -Name UpdateServices ',
	'uninstall feature user-interfaces':'Uninstall-WindowsFeature -Name User-Interfaces-Infra ',
	'uninstall feature volume-activation':'Uninstall-WindowsFeature -Name VolumeActivation',
	'uninstall feature was api':'Uninstall-WindowsFeature -Name WAS-Config-APIs',
	'uninstall feature was':'Uninstall-WindowsFeature -Name WAS ',
	'uninstall feature was-dotnet-env':'Uninstall-WindowsFeature -Name WAS-NET-Environment ',
	'uninstall feature was-proc-model':'Uninstall-WindowsFeature -Name WAS-Process-Model ',
	'uninstall feature wds':'Uninstall-WindowsFeature -Name WDS ',
	'uninstall feature wds-admin-pack':'Uninstall-WindowsFeature -Name WDS-AdminPack ',
	'uninstall feature web-proxy':'Uninstall-WindowsFeature -Name Web-Application-Proxy',
	'uninstall feature wff':'Uninstall-WindowsFeature -Name WFF ',
	'uninstall feature win-identity-foundation':'Uninstall-WindowsFeature -Name Windows-Identity-Foundation ',
	'uninstall feature win-internal-database':'Uninstall-WindowsFeature -Name Windows-Internal-Database ',
	'uninstall feature win-storage-mgmt':'Uninstall-WindowsFeature -Name WindowsStorageManagementService ',
	'uninstall feature win-tiff-ifilter':'Uninstall-WindowsFeature -Name Windows-TIFF-IFilter ',
	'uninstall feature wins':'Uninstall-WindowsFeature -Name WINS ',
	'uninstall feature wireless-networking':'Uninstall-WindowsFeature -Name Wireless-Networking ',
	'uninstall feature wow64-support':'Uninstall-WindowsFeature -Name WoW64-Support ',
	'uninstall feature xps-viewer':'Uninstall-WindowsFeature -Name XPS-Viewer',
	'uninstall ad-cs cert-authority':'Uninstall-WindowsFeature -Name ADCS-Cert-Authority',
	'uninstall ad-cs enrollment ca-service':'Uninstall-WindowsFeature -Name ADCS-Web-Enrollment',
	'uninstall ad-cs enrollment web-service':'Uninstall-WindowsFeature -Name ADCS-Enroll-Web-Svc',
	'uninstall ad-cs enrollment dev-service':'Uninstall-WindowsFeature -Name ADCS-Device-Enrollment',
	'uninstall ad-cs enrollment policy-web-service':'Uninstall-WindowsFeature -Name ADCS-Enroll-Web-Pol ',
	'uninstall ad-cs responder':'Uninstall-WindowsFeature -Name ADCS-Online-Cert',
	'uninstall ad-rights id':'Uninstall-WindowsFeature -Name ADRMS-Identity',
	'uninstall ad-rights server':'Uninstall-WindowsFeature -Name ADRMS-Server',
	'uninstall app-server com':'Uninstall-WindowsFeature -Name AS-Ent-Services',
	'uninstall app-server http':'Uninstall-WindowsFeature -Name AS-HTTP-Activation',
	'uninstall app-server msmq':'Uninstall-WindowsFeature -Name AS-MSMQ-Activation',
	'uninstall app-server named-pipes':'Uninstall-WindowsFeature -Name AS-Named-Pipes',
	'uninstall app-server dotnet45':'Uninstall-WindowsFeature -Name AS-NET-Framework',
	'uninstall app-server tcp':'Uninstall-WindowsFeature -Name AS-TCP-Activation',
	'uninstall app-server tcp-sharing':'Uninstall-WindowsFeature -Name AS-TCP-Port-Sharing',
	'uninstall app-server transaction atomic':'Uninstall-WindowsFeature -Name AS-WS-Atomic',
	'uninstall app-server transaction distributed':'Uninstall-WindowsFeature -Name AS-Dist-Transaction',
	'uninstall app-server transaction incoming':'Uninstall-WindowsFeature -Name AS-Incoming-Trans',
	'uninstall app-server transaction outgoing':'Uninstall-WindowsFeature -Name AS-Outgoing-Trans',
	'uninstall app-server was':'Uninstall-WindowsFeature -Name AS-WAS-Support',
	'uninstall app-server web-support':'Uninstall-WindowsFeature -Name AS-Web-Support',
	'uninstall bitlocker network-unlock':'Uninstall-WindowsFeature -Name BitLocker-NetworkUnlock ',
	'uninstall bits compact-server':'Uninstall-WindowsFeature -Name BITS-Compact-Server ',
	'uninstall bits iis':'Uninstall-WindowsFeature -Name BITS-IIS-Ext ',
	'uninstall dotnet http-activation':'Uninstall-WindowsFeature -Name NET-HTTP-Activation ',
	'uninstall dotnet nonhttp-activation':'Uninstall-WindowsFeature -Name NET-Non-HTTP-Activ ',
	'uninstall dotnet45 aspnet ':'Uninstall-WindowsFeature -Name NET-Framework-45-ASPNET ',
	'uninstall dotnet45 http-activation':'Uninstall-WindowsFeature -Name NET-WCF-HTTP-Activation45 ',
	'uninstall dotnet45 msmq-activation':'Uninstall-WindowsFeature -Name NET-WCF-MSMQ-Activation45 ',
	'uninstall dotnet45 pipe-activation':'Uninstall-WindowsFeature -Name NET-WCF-Pipe-Activation45 ',
	'uninstall dotnet45 tcp-activation':'Uninstall-WindowsFeature -Name NET-WCF-TCP-Activation45 ',
	'uninstall dotnet45 tcp-port-sharing':'Uninstall-WindowsFeature -Name NET-WCF-TCP-PortSharing45 ',
	'uninstall dotnet45 wcf':'Uninstall-WindowsFeature -Name NET-WCF-Services45 ',
	'uninstall hypverv pshell':'Uninstall-WindowsFeature -Name Hyper-V-PowerShell ',
	'uninstall hypverv tools':'Uninstall-WindowsFeature -Name Hyper-V-Tools ',
	'uninstall iis app-dev':'Uninstall-WindowsFeature -Name Web-App-Dev ',
	'uninstall iis app-init':'Uninstall-WindowsFeature -Name Web-AppInit ',
	'uninstall iis asp':'Uninstall-WindowsFeature -Name Web-ASP ',
	'uninstall iis asp-net':'Uninstall-WindowsFeature -Name Web-Asp-Net ',
	'uninstall iis asp-net45':'Uninstall-WindowsFeature -Name Web-Asp-Net45 ',
	'uninstall iis auto-compression':'Uninstall-WindowsFeature -Name Web-Dyn-Compression',
	'uninstall iis basic-auth':'Uninstall-WindowsFeature -Name Web-Basic-Auth',
	'uninstall iis cgi':'Uninstall-WindowsFeature -Name Web-CGI ',
	'uninstall iis client-cert-auth':'Uninstall-WindowsFeature -Name Web-Cert-Auth ',
	'uninstall iis client-hash-auth':'Uninstall-WindowsFeature -Name Web-Digest-Auth',
	'uninstall iis default-doc':'Uninstall-WindowsFeature -Name Web-Default-Doc',
	'uninstall iis dir-browser':'Uninstall-WindowsFeature -Name Web-Dir-Browsing',
	'uninstall iis ftp-ext':'Uninstall-WindowsFeature -Name Web-Ftp-Ext ',
	'uninstall iis ftp-server':'Uninstall-WindowsFeature -Name Web-Ftp-Server ',
	'uninstall iis ftp-service':'Uninstall-WindowsFeature -Name Web-Ftp-Service ',
	'uninstall iis health':'Uninstall-WindowsFeature -Name Web-Health',
	'uninstall iis http-common':'Uninstall-WindowsFeature -Name Web-Common-Http',
	'uninstall iis http-errors':'Uninstall-WindowsFeature -Name Web-Http-Errors',
	'uninstall iis http-redirect':'Uninstall-WindowsFeature -Name Web-Http-Redirect',
	'uninstall iis http-tracing':'Uninstall-WindowsFeature -Name Web-Http-Tracing',
	'uninstall iis hwc':'Uninstall-WindowsFeature -Name Web-HWC ',
	'uninstall iis ip-security':'Uninstall-WindowsFeature -Name Web-IP-Security',
	'uninstall iis isapi':'Uninstall-WindowsFeature -Name Web-ISAPI-Ext ',
	'uninstall iis isapi-filter':'Uninstall-WindowsFeature -Name Web-ISAPI-Filter ',
	'uninstall iis legacy-scripting':'Uninstall-WindowsFeature -Name Web-Lgcy-Scripting ',
	'uninstall iis logging custom':'Uninstall-WindowsFeature -Name Web-Custom-Logging',
	'uninstall iis logging http':'Uninstall-WindowsFeature -Name Web-Http-Logging',
	'uninstall iis logging libs':'Uninstall-WindowsFeature -Name Web-Log-Libraries',
	'uninstall iis logging odbc':'Uninstall-WindowsFeature -Name Web-ODBC-Logging',
	'uninstall iis metabase':'Uninstall-WindowsFeature -Name Web-Metabase ',
	'uninstall iis mgmt-compatibility':'Uninstall-WindowsFeature -Name Web-Mgmt-Compat ',
	'uninstall iis mgmt-console':'Uninstall-WindowsFeature -Name Web-Mgmt-Console ',
	'uninstall iis mgmt-console-legacy':'Uninstall-WindowsFeature -Name Web-Lgcy-Mgmt-Console ',
	'uninstall iis mgmt-service':'Uninstall-WindowsFeature -Name Web-Mgmt-Service ',
	'uninstall iis mgmt-tools':'Uninstall-WindowsFeature -Name Web-Mgmt-Tools ',
	'uninstall iis net':'Uninstall-WindowsFeature -Name Web-Net-Ext ',
	'uninstall iis net-45':'Uninstall-WindowsFeature -Name Web-Net-Ext45 ',
	'uninstall iis odata':'Uninstall-WindowsFeature -Name ManagementOdata ',
	'uninstall iis performance':'Uninstall-WindowsFeature -Name Web-Performance',
	'uninstall iis request-mon':'Uninstall-WindowsFeature -Name Web-Request-Monitor',
	'uninstall iis scripting':'Uninstall-WindowsFeature -Name Web-Scripting-Tools ',
	'uninstall iis security':'Uninstall-WindowsFeature -Name Web-Security',
	'uninstall iis ssi':'Uninstall-WindowsFeature -Name Web-Includes ',
	'uninstall iis ssl-provider':'Uninstall-WindowsFeature -Name Web-CertProvider',
	'uninstall iis static-compression':'Uninstall-WindowsFeature -Name Web-Stat-Compression',
	'uninstall iis static-content':'Uninstall-WindowsFeature -Name Web-Static-Content',
	'uninstall iis url-auth':'Uninstall-WindowsFeature -Name Web-Url-Auth',
	'uninstall iis web-filter':'Uninstall-WindowsFeature -Name Web-Filtering',
	'uninstall iis web-server':'Uninstall-WindowsFeature -Name Web-WebServer',
	'uninstall iis web-sockets':'Uninstall-WindowsFeature -Name Web-WebSockets ',
	'uninstall iis webdav-publishing':'Uninstall-WindowsFeature -Name Web-DAV-Publishing',
	'uninstall iis windows-auth':'Uninstall-WindowsFeature -Name Web-Windows-Auth',
	'uninstall iis winrm':'Uninstall-WindowsFeature -Name WinRM-IIS-Ext ',
	'uninstall iis wmi':'Uninstall-WindowsFeature -Name Web-WMI ',
	'uninstall iscsi branch-cache':'Uninstall-WindowsFeature -Name FS-BranchCache ',
	'uninstall iscsi dedup':'Uninstall-WindowsFeature -Name FS-Data-Deduplication',
	'uninstall iscsi dfs-replicate':'Uninstall-WindowsFeature -Name FS-DFS-Replication',
	'uninstall iscsi dfs-resource-mgmt':'Uninstall-WindowsFeature -Name FS-Resource-Manager',
	'uninstall iscsi dfs-space':'Uninstall-WindowsFeature -Name FS-DFS-Namespace',
	'uninstall iscsi nfs-service':'Uninstall-WindowsFeature -Name FS-NFS-Service',
	'uninstall iscsi server':'Uninstall-WindowsFeature -Name FS-FileServer',
	'uninstall iscsi sync-share':'Uninstall-WindowsFeature -Name FS-SyncShareService',
	'uninstall iscsi target-server':'Uninstall-WindowsFeature -Name FS-iSCSITarget-Server',
	'uninstall iscsi target-vss':'Uninstall-WindowsFeature -Name iSCSITarget-VSS-VDS',
	'uninstall iscsi vss':'Uninstall-WindowsFeature -Name FS-VSS-Agent',
	'uninstall feature linux-subsystem':'Enable-WindowsOptionalFeature -online -FeatureName Microsoft-Windows-Subsystem-Linux -NoRestart',
	'uninstall msmq dcom':'Uninstall-WindowsFeature -Name MSMQ-DCOM ',
	'uninstall msmq directory':'Uninstall-WindowsFeature -Name MSMQ-Directory ',
	'uninstall msmq http-support':'Uninstall-WindowsFeature -Name MSMQ-HTTP-Support ',
	'uninstall msmq multicast':'Uninstall-WindowsFeature -Name MSMQ-Multicasting ',
	'uninstall msmq routing':'Uninstall-WindowsFeature -Name MSMQ-Routing ',
	'uninstall msmq server':'Uninstall-WindowsFeature -Name MSMQ-Server ',
	'uninstall msmq services':'Uninstall-WindowsFeature -Name MSMQ-Services ',
	'uninstall msmq triggers':'Uninstall-WindowsFeature -Name MSMQ-Triggers ',
	'uninstall npas health':'Uninstall-WindowsFeature -Name NPAS-Health',
	'uninstall npas host-authorization':'Uninstall-WindowsFeature -Name NPAS-Host-Cred',
	'uninstall npas policy-server':'Uninstall-WindowsFeature -Name NPAS-Policy-Server',
	'uninstall rdp connection-broker':'Uninstall-WindowsFeature -Name RDS-Connection-Broker',
	'uninstall rdp gateway':'Uninstall-WindowsFeature -Name RDS-Gateway',
	'uninstall rdp licensing':'Uninstall-WindowsFeature -Name RDS-Licensing',
	'uninstall rdp session-host':'Uninstall-WindowsFeature -Name RDS-RD-Server',
	'uninstall rdp virtual':'Uninstall-WindowsFeature -Name RDS-Virtualization',
	'uninstall rdp web-access':'Uninstall-WindowsFeature -Name RDS-Web-Access',
	'uninstall rsat ad-admin-center':'Uninstall-WindowsFeature -Name RSAT-AD-AdminCenter ',
	'uninstall rsat ad-cs':'Uninstall-WindowsFeature -Name RSAT-ADCS ',
	'uninstall rsat ad-cs-mgmt':'Uninstall-WindowsFeature -Name RSAT-ADCS-Mgmt ',
	'uninstall rsat ad-ds':'Uninstall-WindowsFeature -Name RSAT-ADDS ',
	'uninstall rsat ad-ds-tools':'Uninstall-WindowsFeature -Name RSAT-ADDS-Tools ',
	'uninstall rsat ad-lds':'Uninstall-WindowsFeature -Name RSAT-ADLDS ',
	'uninstall rsat ad-pshell':'Uninstall-WindowsFeature -Name RSAT-AD-PowerShell ',
	'uninstall rsat ad-rights':'Uninstall-WindowsFeature -Name RSAT-ADRMS ',
	'uninstall rsat ad-tools':'Uninstall-WindowsFeature -Name RSAT-AD-Tools ',
	'uninstall rsat bitlocker-admin':'Uninstall-WindowsFeature -Name RSAT-Feature-Tools-BitLocker',
	'uninstall rsat bitLocker-encryption':'Uninstall-WindowsFeature -Name RSAT-Feature-Tools-BitLocker-RemoteAdminTool ',
	'uninstall rsat bitlocker-recovery':'Uninstall-WindowsFeature -Name RSAT-Feature-Tools-BitLocker-BdeAducExt ',
	'uninstall rsat bits-server':'Uninstall-WindowsFeature -Name RSAT-Bits-Server ',
	'uninstall rsat clustering command-int':'Uninstall-WindowsFeature -Name RSAT-Clustering-CmdInterface ',
	'uninstall rsat clustering':'Uninstall-WindowsFeature -Name RSAT-Clustering ',
	'uninstall rsat clustering-automation':'Uninstall-WindowsFeature -Name RSAT-Clustering-AutomationServer ',
	'uninstall rsat clustering-mgmt':'Uninstall-WindowsFeature -Name RSAT-Clustering-Mgmt ',
	'uninstall rsat clustering-pshell':'Uninstall-WindowsFeature -Name RSAT-Clustering-PowerShell ',
	'uninstall rsat core-file-mgmt':'Uninstall-WindowsFeature -Name RSAT-CoreFile-Mgmt ',
	'uninstall rsat dfs-mgmt':'Uninstall-WindowsFeature -Name RSAT-DFS-Mgmt-Con ',
	'uninstall rsat dhcp':'Uninstall-WindowsFeature -Name RSAT-DHCP ',
	'uninstall rsat dns':'Uninstall-WindowsFeature -Name RSAT-DNS-Server',
	'uninstall rsat fax':'Uninstall-WindowsFeature -Name RSAT-Fax ',
	'uninstall rsat feature-tools':'Uninstall-WindowsFeature -Name RSAT-Feature-Tools ',
	'uninstall rsat file-services':'Uninstall-WindowsFeature -Name RSAT-File-Services ',
	'uninstall rsat fsrm-mgmt':'Uninstall-WindowsFeature -Name RSAT-FSRM-Mgmt ',
	'uninstall rsat hyperv':'Uninstall-WindowsFeature -Name RSAT-Hyper-V-Tools',
	'uninstall rsat license-check':'Uninstall-WindowsFeature -Name RSAT-RDS-Licensing-Diagnosis-UI ',
	'uninstall rsat license-ui':'Uninstall-WindowsFeature -Name RDS-Licensing-UI ',
	'uninstall rsat nfs-admin':'Uninstall-WindowsFeature -Name RSAT-NFS-Admin ',
	'uninstall rsat nis':'Uninstall-WindowsFeature -Name RSAT-NIS ',
	'uninstall rsat nlb':'Uninstall-WindowsFeature -Name RSAT-NLB ',
	'uninstall rsat npas':'Uninstall-WindowsFeature -Name RSAT-NPAS ',
	'uninstall rsat print-services':'Uninstall-WindowsFeature -Name RSAT-Print-Services ',
	'uninstall rsat rds-gateway':'Uninstall-WindowsFeature -Name RSAT-RDS-Gateway ',
	'uninstall rsat rds-tools':'Uninstall-WindowsFeature -Name RSAT-RDS-Tools ',
	'uninstall rsat remote-access':'Uninstall-WindowsFeature -Name RSAT-RemoteAccess ',
	'uninstall rsat remote-access-mgmt':'Uninstall-WindowsFeature -Name RSAT-RemoteAccess-Mgmt ',
	'uninstall rsat remote-access-pshell':'Uninstall-WindowsFeature -Name RSAT-RemoteAccess-PowerShell ',
	'uninstall rsat responder':'Uninstall-WindowsFeature -Name RSAT-Online-Responder ',
	'uninstall rsat role-tools':'Uninstall-WindowsFeature -Name RSAT-Role-Tools ',
	'uninstall rsat smtp':'Uninstall-WindowsFeature -Name RSAT-SMTP ',
	'uninstall rsat snmp':'Uninstall-WindowsFeature -Name RSAT-SNMP ',
	'uninstall rsat va-tools':'Uninstall-WindowsFeature -Name RSAT-VA-Tools ',
	'uninstall rsat wins':'Uninstall-WindowsFeature -Name RSAT-WINS ',
	'uninstall update-service ui':'Uninstall-WindowsFeature -Name UpdateServices-UI ',
	'uninstall update-services api':'Uninstall-WindowsFeature -Name UpdateServices-API ',
	'uninstall update-services database':'Uninstall-WindowsFeature -Name UpdateServices-DB ',
	'uninstall update-services rsat':'Uninstall-WindowsFeature -Name UpdateServices-RSAT ',
	'uninstall update-services services':'Uninstall-WindowsFeature -Name UpdateServices-Services ',
	'uninstall update-services widdb':'Uninstall-WindowsFeature -Name UpdateServices-WidDB ',
	'uninstall wds deployment':'Uninstall-WindowsFeature -Name WDS-Deployment ',
	'uninstall wds transport':'Uninstall-WindowsFeature -Name WDS-Transport | Out-Null',
	'uninstall wds admin-pack':'Uninstall-WindowsFeature -Name WDS-AdminPack | Out-Null',
}